version: '3'

services:
 mongo:
  container_name: mongodb
  restart: always
  image: mongo:4.4.18
  environment:
    MONGO_INITDB_ROOT_USERNAME: 'devbills'
    MONGO_INITDB_ROOT_password: 'devbills'
  ports:
   - '27017:27017'
  networks:
   - local

 app:
  depends_on:
   - mongo
  container_name: devbills-api
  build:
   context: .
   dockerfile: dockerfile
  volumes:
   - ./:/home/app
  ports:
   - '3333:3333'
  networks:
   - local

networks:
 local:
  name: local